# Generated by Django 4.2.7 on 2023-11-27 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cus_lname', models.CharField(max_length=45)),
                ('cus_fname', models.CharField(max_length=45)),
                ('cus_initial', models.CharField(blank=True, max_length=45, null=True)),
                ('cus_email', models.CharField(max_length=128)),
                ('cus_phone', models.CharField(max_length=12)),
                ('cus_phone_country', models.CharField(max_length=3)),
                ('cus_password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('disc_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('disc_code', models.CharField(max_length=16)),
                ('disc_start', models.DateTimeField()),
                ('disc_end', models.DateTimeField()),
                ('disc_amount', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'db_table': 'DISCOUNT',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('inv_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('inv_date', models.DateTimeField()),
                ('inv_address_line1', models.CharField(max_length=128)),
                ('inv_address_line2', models.CharField(blank=True, max_length=128, null=True)),
                ('inv_address_city', models.CharField(max_length=128)),
                ('inv_address_region', models.CharField(max_length=128)),
                ('inv_address_country', models.CharField(max_length=128)),
                ('inv_address_postalcode', models.CharField(max_length=16)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BookFair.customer')),
            ],
            options={
                'db_table': 'INVOICE',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=128)),
                ('prod_descript', models.CharField(max_length=2048)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prod_stock', models.PositiveIntegerField()),
                ('prod_img', models.ImageField(null=True, upload_to='product')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookFair.category')),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('line_total', models.DecimalField(db_comment='The monetary amount that the items in this line were sold for, after a discount was applied.', decimal_places=2, max_digits=8)),
                ('line_quantity', models.PositiveIntegerField()),
                ('disc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BookFair.discount')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookFair.invoice')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BookFair.product')),
            ],
            options={
                'db_table': 'LINE',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='BookFair.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BookFair.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='BookFair.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookFair.userprofile'),
        ),
    ]
